"""add_pantry_tables

Revision ID: 31aab91d2737
Revises: d80b90ec79ae
Create Date: 2026-01-06 18:24:52.022700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31aab91d2737'
down_revision: Union[str, None] = 'd80b90ec79ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantry_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('receipt_item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('IN_STOCK', 'CONSUMED', 'WASTED', name='pantrystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['receipt_item_id'], ['receipt_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pantry_items_id'), 'pantry_items', ['id'], unique=False)
    op.drop_index('ix_chat_history_id', table_name='chat_history')
    op.drop_table('chat_history')
    op.add_column('products', sa.Column('typical_shelf_life', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'typical_shelf_life')
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('query', sa.TEXT(), nullable=False),
    sa.Column('response', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('context', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_history_id', 'chat_history', ['id'], unique=False)
    op.drop_index(op.f('ix_pantry_items_id'), table_name='pantry_items')
    op.drop_table('pantry_items')
    # ### end Alembic commands ###

